In [1]:
import numpy as np
import pandas as pd

from rice_ml.supervised_learning import (euclidean_distance, manhattan_distance)

df = pd.read_csv("../data/lesions_processed.csv")

X = df[["x_norm", "y_norm", "slice_norm"]].values
X[:5]


array([[0.67857143, 0.94540943, 0.1984127 ],
       [0.74369748, 0.7146402 , 0.15079365],
       [0.34243697, 0.47394541, 0.15674603],
       [0.71008403, 0.60297767, 0.18650794],
       [0.32773109, 0.33498759, 0.08928571]])

In [2]:
#compare distance
a = X[0]
b = X[1]

euclidean_distance(a, b), manhattan_distance(a, b)


(0.24446556814671871, 0.3435143288084467)

In [3]:
#comapare across multi points
pairs = [(0, 1), (0, 2), (1, 3)]

for i, j in pairs:
    e = euclidean_distance(X[i], X[j])
    m = manhattan_distance(X[i], X[j])
    print(f"Points {i}-{j}: Euclidean={e:.4f}, Manhattan={m:.4f}")


Points 0-1: Euclidean=0.2445, Manhattan=0.3435
Points 0-2: Euclidean=0.5805, Manhattan=0.8493
Points 1-3: Euclidean=0.1220, Manhattan=0.1810


In [4]:
#distance matrix
n = 5
D_euc = np.zeros((n, n))
D_man = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        D_euc[i, j] = euclidean_distance(X[i], X[j])
        D_man[i, j] = manhattan_distance(X[i], X[j])

D_euc, D_man


(array([[0.        , 0.24446557, 0.5805177 , 0.3440847 , 0.71246927],
        [0.24446557, 0.        , 0.46795235, 0.12195858, 0.56652216],
        [0.5805177 , 0.46795235, 0.        , 0.39076778, 0.15516582],
        [0.3440847 , 0.12195858, 0.39076778, 0.        , 0.4769325 ],
        [0.71246927, 0.56652216, 0.15516582, 0.4769325 , 0.        ]]),
 array([[0.        , 0.34351433, 0.84926514, 0.38584913, 1.07038916],
        [0.34351433, 0.        , 0.64790767, 0.18099026, 0.85712693],
        [0.84926514, 0.64790767, 0.        , 0.52644122, 0.22112402],
        [0.38584913, 0.18099026, 0.52644122, 0.        , 0.74756524],
        [1.07038916, 0.85712693, 0.22112402, 0.74756524, 0.        ]]))